[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"

[project]
# The name pyo3_pure instead of pyo3-pure is intentional,
# it's used as a crate name resolution regression test
name = "pyo3_pure"
version = "0.1.0+abc123de"
classifiers = [
    "Programming Language :: Rust"
]
description = "Implements a dummy function in Rust"
readme = "README.md"
maintainers = [
    {name = "messense", email = "messense@icloud.com"}
]
license = { file = "LICENSE" }

[project.optional-dependencies]
test = [
    "attrs",
    "boltons; sys_platform == 'win32'"
]

[project.scripts]
get_42 = "pyo3_pure:DummyClass.get_42"

[project.gui-scripts]
get_42_gui = "pyo3_pure:DummyClass.get_42"
